### ISSUE TITLE
Example Links

### ISSUE THREAD

**Issue by M3ssman** [qurator-spk/neat#53]
Hello,

looking for a quick startup I stumbled over the links provided on top of both example.tsv-files (https://content.staatsbibliothek-berlin.de/dc/PPN757123368-00000008/left,top,width,height/full/0/default.jpg, https://content.staatsbibliothek-berlin.de/dc/PPN757123368-00000008/left,top,width,height/full/0/default.jpg) , but unfortunately, they are currently leading nowhere.

**Comment by labusch** [comment]
Hi,
The link as it is stored in the tsv files contains placeholders that are replaced by neat with valid coordinates in order to depict a particular part of the image.

The placeholders are "left,top,width,height", for instance:
https://content.staatsbibliothek-berlin.de/dc/PPN757123368-00000008/100,100,200,200/full/0/default.jpg
gives a valid image link.

Best regards,
Kai

**Comment by cneud** [comment]
Hi Uwe, we use our [IIIF endpoints](https://lab.sbb.berlin/zefys/) in neat, so the part that comes after the `baseurl` and `PPN` is regular IIIF Image API syntax. We take the coordinates from the TSV that is produced from OCR in PAGE-XML file via https://github.com/qurator-spk/page2tsv.
